version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: testpassword
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: test
      PMA_PASSWORD: testpassword
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  db_data:
